### ISSUE TITLE
Segmentation Fault - Compiling in Qt project

### ISSUE THREAD

**Issue by pindamonhangaba** [neubig/kytea#15]
I am trying to compile kytea in a Qt project, following the `api-example.cpp`, and I get a segmentation fault at `kytea-config.cpp:286` when attempting to delete `util_`:

    284    void KyteaConfig::setEncoding(const char* str) {
    285        if(util_)
    286            delete util_;
    287        if(!strcmp(str,"utf8")) util_ = new StringUtilUtf8();
    288        else if(!strcmp(str,"euc")) util_ = new StringUtilEuc();
    289        else if(!strcmp(str,"sjis")) util_ = new StringUtilSjis();
    290        else
    291            THROW_ERROR("Unsupported encoding format '" << str << "'");
    292    }

It appears that `config.setEncoding(buff4.c_str());` get's called, at `model-io.cpp:62`, after `util_` was already deleted at `kytea-config.cpp:334`

    332    KyteaConfig::~KyteaConfig() {
    333        if(util_)
    334            delete util_;
    335    }

**Comment by neubig** [comment]
Hi, thanks for the bug report!
Just to confirm, api-example.cpp works fine in your environment correct?
If so, then the problem is probably not in the KyTea code, but the code that is calling it. If you can provide your example code I might be able to help more.

**Comment by pindamonhangaba** [comment]
You are right, the model loading was inside a controller, and that was probably the issue. Maybe related to the short lifespan of the controller.
