### ISSUE TITLE
Smallest word tokenizing 

### ISSUE THREAD

**Issue by pindamonhangaba** [neubig/kytea#16]
Kytea seems to go for the smallest word possible, first come-first serve style, even on very basic words like `おばあさん` and `おじいさん`, dividing them both as `お-ばあ-さん` and `お-じい-さん`. This was generated using the `jp-0.4.7-5.mod` and the `api-example.cpp` sample.

**Comment by neubig** [comment]
These segmentations follow the Japanese segmentation standard for the standard KyTea model, so this is not a mistake. You can find more details here (in the BCCWJ section): http://phontron.com/kytea/train.html#data

If you want a model that segments these as a single word you can train a model yourself, but we don't plan to officially support segmentation of other granularities.
